### ISSUE TITLE
Add link to tasks.txt in menu

### ISSUE THREAD

**Issue by statnmap** [gtimelog/gtimelog#101]
Hi,
In the File menu, there is a link to timelog.txt but not to tasks.txt.
Could you add it so that I do not have to search for it each time I want to add a new task to the list ?
Except if I missed something...?

By the way, when I installed gtimelog with the official ubuntu repository, this tasks.txt file did not exist in ~/.local/share/gtimelog/. I had to create it.

Thanks

**Comment by mgedmin** [comment]
This is fixed in current git master:
![screenshot](https://cloud.githubusercontent.com/assets/159967/23557888/557ec9bc-003a-11e7-8aff-69174cdc8122.png)
