### ISSUE TITLE
Assumes 8 hour working day

### ISSUE THREAD

**Issue by goetzk** [gtimelog/gtimelog#102]
Hi,
There appears to be a hard coded assumption of an 8 hour working day, for example here in scripts/today.py.
https://github.com/gtimelog/gtimelog/blob/09b481899d7eab01f0ae5cdf8bb9209d02bf477a/scripts/today.py#L140

It would be great to have that moved in to the configuration file to better reflect peoples working days.

**Comment by mgedmin** [comment]
`scripts/` are a historical curiosity, nothing more.  The reporting code in gtimelog itself is configurable.

**Comment by goetzk** [comment]
My bad! I'll look up the config and fix up my workflow.

Thanks!

**Comment by mgedmin** [comment]
If you want a non-interactive script to generate reports for you, I have an open wishlist bug for that: https://github.com/gtimelog/gtimelog/issues/74

**Comment by rzelnik** [comment]
So how can I change the number of hours per working day?

**Comment by mgedmin** [comment]
@rzelnik assuming you use a recent release (starting with 0.11, which was released in March 2018) you can hit Ctrl+P to get the Preferences window.  (It's also accessible from the GNOME application menu, which is so notoriously undiscoverable that GNOMErs are thinking about deprecating it).

**Comment by rzelnik** [comment]
@mgedmin thanks for your info. I already discovered the Preferences menu item. I actually discover the global menu regularly and it always surprises me.
