### ISSUE TITLE
Debian packaging for gtimelog 0.11

### ISSUE THREAD

**Issue by mgedmin** [gtimelog/gtimelog#105]
This is a continuation of #61.  Version 0.11 of gtimelog (out on PyPI today) introduced new data files:

- `org.gtimelog.gschema.xml` (in `src/gtimelog/data`), which needs to be installed into `/usr/share/glib-2.0/schemas` and compiled with `glib-compile-schemas`
- gettext translations (`src/gtimelog/locale`, built by `make`), which need to be installed to `/usr/share/locale/`
- `gtimelog.desktop` which needs to be installed into `/usr/share/applications/` (and possibly be renamed to `org.gtimelog.desktop`)
- `gtimelog.appdata.xml`, which needs to go to `/usr/share/appdata/` (and possibly be renamed to `org.gtimelog.appdata.xml`)
- help files (`src/gtimelog/help`), which need to go to `/usr/share/help/`

Then I need to update `main.py` to look for these files in those locations, and then I need to strip them away from site-packages/dist-packages.

For completeness here are the old files that are still needed
- the icon (`src/gtimelog/gtimelog-large.png`), which needs to go to, uh, ... I dunno, `/usr/share/pixmaps`?
- the man page (`gtimelog.1`, built by `make`), which needs to be gzipped and go to `/usr/share/man/man1/`

I want to upload the produced debs into the gtimelog PPA, and, ideally, get them into Debian and Ubuntu at some point.  (Hi, @warsaw!)

**Comment by mgedmin** [comment]
The current Debian packaging lives at https://anonscm.debian.org/cgit/collab-maint/gtimelog.git.

I could probably find useful documentation at https://wiki.debian.org/Teams/PythonAppsPackagingTeam.

**Comment by mgedmin** [comment]
0.11 is in Debian unstable!

https://packages.qa.debian.org/g/gtimelog/news/20180228T073615Z.html

**Comment by andrewshadura** [comment]
Because of my incredible attention to the details, it took me four attempts to get things right in the packaging, which led to the package going through the NEW queue, which will take some time.

**Comment by mgedmin** [comment]
I've created a `ppa` branch that merges the `debian/master` packaging branch from salsa on top of the 0.11 tag and adds some tweaks to make it build on Ubuntu xenial (no debhelper 11) plus Makefile rules to produce and upload Debian source packages to the PPA.

Version 0.11-4mg1 (that should've been -4ppa0 or sth) is [currently building on Launchpad](https://launchpad.net/~gtimelog-dev/+archive/ubuntu/ppa/+build/14424086).

**Comment by mgedmin** [comment]
0.11 is now available from the PPA.

(I have not tested it personally because I'm a bad maintainer.)
