### ISSUE TITLE
Are tags synonymous with releases?

### ISSUE THREAD

**Issue by goetzk** [gtimelog/gtimelog#112]
Hi,
I'm looking at all the changes since the last release and wondering if the (recently added) tags should be considered releases themselves.
thanks,
kk

**Comment by mgedmin** [comment]
Ah!  I completely forgot that I used to use the GitHub "releases" feature a few years back!  I wish it could be automated...

**Comment by mgedmin** [comment]
Thank you for the reminder.  I've converted the 0.11 tag to a release.  I don't know if it's worth doing that for older tags?  I'm essentially copying and pasting bits from the changelog (CHANGES.rst in each branch).

**Comment by goetzk** [comment]
Thanks for creating the release. I wouldn't bother with the older releases, I'm not even sure its worth doing routinely at all. Perhaps there just needs to be a note made that tags are releases and be done with it?
