### ISSUE TITLE
Entries without task not shown in categorial summary. 

### ISSUE THREAD

**Issue by codingforfun** [gtimelog/gtimelog#117]
If I create entries just with a category and without a task they are summed up by category in the categorical summary view, but instead summed up under `no category`. 
Steps to reproduce:
+ Create entries without task. E.g. `2018-07-11 12:00: ProjectFoo: ` 
+ Create entries with task. E.g. `2018-07-11 12:00: ProjectBar: Coding #1234 ` 
+ Switch to `View time spent on each task category` view (`Alt+3`)
+ You will see entries summed up as `ProjectBar` and `no category`. I think the expected result should rather be `ProjectBar` and `ProjectFoo`.

**Comment by mgedmin** [comment]
Thank you for reporting this bug!  I'll take a look.

**Comment by mgedmin** [comment]
Should be fixed in git master.

**Comment by codingforfun** [comment]
Great. Thank you.
