### ISSUE TITLE
Category view (Alt+3) summary without task. 

### ISSUE THREAD

**Issue by codingforfun** [gtimelog/gtimelog#120]
I hope I don’t spam you here. This is somewhat similar topic as https://github.com/gtimelog/gtimelog/issues/91 but I think it’s still maybe a bug so I didn’t wanted to clutter the other issue with possible of topic. 

Can you please elaborate a bit about what’s idea behind the category summery? 

What confuses me is the following: 
* If I add task descriptions to a project time log entries like `2018-07-20 09:15: ProjectFoo: Doing stuff`, than these entries get summarized with the time per project name like so `8h 10min ProjectFoo`. 

* If I leave the task description out like `2018-07-20 09:15: ProjectFoo: `, than these entries get summarized just as `no category`. I don’t really understand why. Since the summary is only about the part before the `:` it shouldn’t matter and I think it would be very useful to keep summarizing them per project. 

Is this a bug or did I just don’t get the concept of this view?

**Comment by mgedmin** [comment]
That is a bug (originally reported as #117), the parser splits the group name from the task on `: ` (colon space), and when there's no space, it thinks this is just a task with no group.

This was fixed recently in git master, but I haven't made a release with the fix yet.

**Comment by codingforfun** [comment]
THX, sorry for duplication. Didn’t find it during search.

**Comment by codingforfun** [comment]
Oh, I created the issue myself. Damn. Where was my head. It’s to hot currently.
