### ISSUE TITLE
Can we schedule it to open every 30 mins?

### ISSUE THREAD

**Issue by lachi87** [gtimelog/gtimelog#121]
Can we design this software to open every 30 mins so that user need not remember to open every time.

**Comment by mgedmin** [comment]
I'm not very keen on adding this feature to gtimelog itself.

If you run `gtimelog` every 30 minutes, it'll bring the existing window to front.  A user's crontab ought to work, if you set the right `DBUS_SESSION_BUS_ADDRESS` in the environment for the cron job (e.g. for me it's always set to `unix:path=/run/user/1000/bus`).

**Comment by jbeyers** [comment]
My 2 cents: I've been using gtimelog via cron for years now with minimal problems. The crontab allows for fine-grained scheduling without having to build that into gtimelog. On pomodoro days, I touch /tmp/pomodoro.flag and my crontab looks like this:
30 8-16 * * * test -f /tmp/pomodoro.flag && DISPLAY=:0.0 gtimelog
0 8-17 * * * test -f /tmp/pomodoro.flag && DISPLAY=:0.0 gtimelog
