### ISSUE TITLE
File change detection doesn't work

### ISSUE THREAD

**Issue by cloutierjo** [gtimelog/gtimelog#128]
On the 0.11 version the file change detection doesn't work anymore. I use gtimelog on to computer with the file synced with dropbox. with the older version, I used to see the change almost instantly, but now I need to close gtimelog and reopen it to see the updated task. Even adding a new task doesn't load the right data. but at least, it dosn't ovewrite anything added from the other computer so a restart of gtimelog give the right amount of time spent.

I'm using gtimelog on a kde desktop, so it might be related.

Regards,

**Comment by mgedmin** [comment]
Older versions of gtimelog used polling (checked the file's modification time every second).  Starting with 0.11 gtimelog uses the Glib's [`g_file_monitor_file()`](https://developer.gnome.org/gio/stable/GFile.html#g-file-monitor-file) which, I think, uses inotify under the hood when it's available (but should fall back to polling when it's not).

I would be surprised to discover that glib is buggy in this respect, so maybe there's something I'm doing wrong?  (E.g. if symlinks are involved, does the glib API track changes to the symlink's target?)

Can you tell me how you have your Dropbox sync set up?  (E.g. are you setting `$GTIMELOG_HOME`?  Are you symlinking the gtimelog data directory?  Are you symlinking the timelog.txt file?)

I have a Dropbox account. but I don't currently have the dropbox client installed on my laptop.  I'll try to see if I can reproduce the issue.

**Comment by cloutierjo** [comment]
I do use symlink on the file itself.
 
Those are not the exact path but here is the config I use:

~/.gtimlog/timelog.txt -> ~/dropbox/timelog.txt

I also remember having similar issues with file monitoring when the watched path was going thru a symlink folder (was with mvn sass:watch I think it use inotify as well but I'm not certain of it)

**Comment by mgedmin** [comment]
Oh yeah, I can reproduce if I replace timelog.txt with a symlink!

**Comment by mgedmin** [comment]
This should be fixed now in git master.
