### ISSUE TITLE
what are the dependencies to install and run gtimelog?

### ISSUE THREAD

**Issue by sam-github** [gtimelog/gtimelog#135]
I've run gtimelog for years in the past and loved it, but am having the devil of a time installing it this time on ubuntu 18.10.

Run from official packages as well as run from source all have this error:

```
gtimelog (master * u=) % ./gtimelog
Traceback (most recent call last):
  File "./gtimelog", line 12, in <module>
    from gtimelog.main import main
  File "/home/sam/s/gtimelog/src/gtimelog/main.py", line 63, in <module>
    gi.require_version('Soup', '2.4')
  File "/home/sam/.local/lib/python2.7/site-packages/gi/__init__.py", line 129, in require_version                                                                           
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Soup not available
```
`make install` failed until I hunted down and installed `python-docutils` and `gettext`, but  then I just rant into above error, the same one I got when trying the official ubuntu gtimelog package.

I then tried pip, it failed to, after hunting down and installing more dependencies, `pkg-config`, `libcairo-dev`, and `libgirepository1.0-dev`, it "suceeded"... but I'm not sure where it put gtimelog. Not in my PATH :-(.

I was hoping the pip would have installed enough deps that the gtimelog git clone would now run, but still, no `Soup` for me.

I'm not sure what soup is required, or where to install it.

Suggestions?

**Comment by sam-github** [comment]
Ouph. Sorry. The last method I tried seems to have worked, using the PPA. And it runs from git now, expected I guess.

Turns out the missing packages were gir1.2-soup, also gir1.2-appindicator3. I'll PR some text to the README to help others.

**Comment by mgedmin** [comment]
There's a file called `other-requirements.txt` that lists Debian packages needed, but I forgot to add the soup dependency to it.  (Also, it's not mentioned in the README!)

git1.2-appindicator3 should not be required any more starting with version 0.11.

**Comment by sam-github** [comment]
In #136 I merged the files, and added the pip dependencies.

**Comment by mgedmin** [comment]
I made gtimelog print a better error message when the introspection typelib files are missing:

```
Typelib files for Soup-2.4 are not available.

If you're on Ubuntu or another Debian-like distribution, please install
them with

    sudo apt install gir1.2-soup-2.4

```

If anyone knows what the packages (and the command to install them) look like on Red Hat based distros, I'd love a tip.
