### ISSUE TITLE
Critical Gtk+ warnings on startup

### ISSUE THREAD

**Issue by mgedmin** [gtimelog/gtimelog#14]
Current master emits this:

```
$ ./gtimelog
(gtimelog:8302): Gtk-CRITICAL **: gtk_radio_menu_item_set_group: assertion '!g_slist_find (group, radio_menu_item)' failed

(gtimelog:8302): Gtk-CRITICAL **: gtk_radio_menu_item_set_group: assertion '!g_slist_find (group, radio_menu_item)' failed
```

I wonder if there's an environment variable that would convert these into Python tracebacks?

**Comment by JohnCC330** [comment]
We're more than a year later... I just hit the problem with set_group(). Using set_property('group', group) works... Thanks for the hint! (I didn't use glade or gtkbuilder).
