### ISSUE TITLE
Couldn't send email to...

### ISSUE THREAD

**Issue by clrh** [gtimelog/gtimelog#140]
Thank you for the app, I like it :)

I got a `Couldn't send email to claire.blabla` in Report feature. 

* What are the prerequisites to have this feature ?
* Is there another way to export in a csv format ?

Thanks a lot,
Regards,
Claire.

**Comment by mgedmin** [comment]
> What are the prerequisites to have this feature ?

Currently gtimelog expects the computer to have a local mail transfer agent installed and configured.  This can be a full-blown MTA like postfix, or something simpler, as long as it ships a /usr/sbin/sendmail.

I have a [pull request half-ready](https://github.com/gtimelog/gtimelog/pull/129) that will make gtimelog use a configured SMTP server directly.

> Is there another way to export in a csv format ?

Not conveniently, at the moment!  gtimelog 0.10 had an "Export to spreadsheet" function (two of them actually) that wrote a CSV file and launched a configured spreadsheet program.  The functions that do the export still exist in the code base, there's just no user interface to access them.

    


I apologize for the inconvenience!

**Comment by mgedmin** [comment]
The SMTP support PR was merged, and there's a separate ticket for CSV export (#167), so I'm going to close this ticket.
