### ISSUE TITLE
Differences between gtimelog and gocept.gtimelog.

### ISSUE THREAD

**Issue by sallner** [gtimelog/gtimelog#160]
A historical overview: `gocept.gtimelog` is a fork of gtimelog created long ago
(~ 2005) with the main intent to upload the resulting timelog entries to the
accounting service collmex and several ticket system like Redmine or Jira. The
simple mail report was not sufficient for the needs of gocept to report to
customers.

Over the time the two versions diverged too much to allow for an easy rebase or
a re-integration of the upstream code. But as GTK-2 is not an option for
current OS anymore the aim is to include part of the changes directly in
upstream gtimelog and a different maybe in form of plugins. 

The following features have been are present in the graphical user interface and that are important to gocept:

- [X] Reload with CTRL-R -> There is an auto-reload now.
- [ ] Delete Last with CTRL-L. This inserts the title of the entry in the inputline making it easy to be modified.
- [ ] A progress bar of work for the week via CTRL-W
- [x] A fuzzy search autocompletion function for the input line , which searches the history.  #218 

The following features are connected with the additional reporting functions:

- [ ] Upload of time entries to respective tickets in Redmine and Jira
- [ ] Upload of time entries to respective customer projects to Collmex
- [ ] Use of an additional tasklist which can be updated from active Collmex projects.
- [ ] GUI entry and short cut for upload to (a) Bugtracker  CTRL-G and (b) Collmex CTRL-O

We also developed a few CLI commands:

- [ ] gtl-upload A single command to upload to bugtracker and Collmex.
- [ ] gtl-progress Show progress of the last week and year. 
- [ ] gtl-log Create a single time entry from CLI.
- [ ] gtl-updatetasks Update the task list from collmex.

I would like to keep this issue as a summary and for tracking the progress of the merge. 

@mgedmin I would be glad if you could indicate which features could make it directly to the upstream code without the need for a plugin.

**Comment by mgedmin** [comment]
Ooh, delete last sounds interesting!

I'm intrigued by the "progress bar" concept and would like to know more.  A screenshot would be lovely.

I currently use https://github.com/ProgrammersOfVilnius/gtimelog2jira to upload a subset of tasks to a Jira instance.  It would be nice to have this available as a plugin, once gtimelog gets a plugin infrastructure.  (I wonder if there are any existing Python/GTK apps that do plugins that would be useful as examples to copy?)

Remote tasklist is an experimental feature that currently exists:
- it can fetch tasks from an HTTPS server (and supports HTTP basic authentication with system keyring integration)
- it expects plain text output with one task per line
- it has no configuration UI at the moment, but can be enabled with dconf-editor or gsettings from the command line

Can this be extended in a way to make it useful to you for Collmex projects?  I've no idea what Collmex is or how it exports available tasks.

I like the command-line version of entering a single entry.  I would like to make `gtimelog --add "entry"` work on the command line (bonus points if it can be made to work without any GUI imports).

I'm also intrigued by `gtl-progress`.  I expect it prints the information to stdout?  I'd like to see an example (anonymized maybe).

The Redmine/Jira/Collmex integration bits sound like plugins.
