### ISSUE TITLE
Change default text editor

### ISSUE THREAD

**Issue by ChameleonScales** [gtimelog/gtimelog#162]
Is it possible to change which text editor is used when clicking on File > Edit timelog.txt ?
Currently it opens with gedit and I'd like it to open with another editor by default (I know I can just run a command but I'm just asking in case there's a simpler way).

I'm on Debian 9 XFCE and I didn't find a system-wide setting to define a preferred text application and my .txt files already open with Geany when open from the file browser so I assume there's a setting in gtimelog to force open with gedit.

**Comment by mgedmin** [comment]
See https://github.com/gtimelog/gtimelog/issues/113#issuecomment-390159049.
