### ISSUE TITLE
Missing choice for week/month on Ubuntu 18 / Gnome 3

### ISSUE THREAD

**Issue by sma-ops** [gtimelog/gtimelog#165]
There is no menu visible to chose previous or a specific week/month for reporting.

I use:
gtimelog: 0.11 (distro package)
gnome 3.28.2 (distro package)
ubuntu 18.04.3

**Comment by mgedmin** [comment]
The arrow buttons in the headerbar are for choosing specific days/weeks/months.  There are also shortcut keys (Alt+Left/Right, and Alt+Home to go back to today/this week/this month).

If these buttons are missing on your system please reopen the bug and attach a screenshot.
