### ISSUE TITLE
What's that "hidden option in gsettings"?

### ISSUE THREAD

**Issue by ChameleonScales** [gtimelog/gtimelog#168]
In the documentation, there's this paragraph that starts with:
> There's a hidden option in gsettings for fetching the task list from an Internet URL.

Could you be more specific about how we set this up? I'm not quite familiar with gsettings.

**Comment by mgedmin** [comment]
dconf-editor is probably the least user-hostile way of accessing this at the moment.  Go to /org/gtimelog/, and you'll find a remote-task-list switch and a task-list-url option.  Set the latter to some HTTPS URL that returns your tasks in plain text, one task per line.

You may also want to set the task-list-edit-url option to another URL that will be opened if you hit Ctrl+T in gtimelog (or choose "Edit task list" from the hamburger menu).

**Comment by ChameleonScales** [comment]
Is /org supposed to be in the root folder of my system? Because it's not (I'm on Debian 10.2).
Do I just have to create it?

**Comment by mgedmin** [comment]
/org/gtimelog  is a dconf path, not a filesystem path.  You should see it in dconf-editor.

![Ekrano nuotrauka iš 2019-12-30 11-01-08](https://user-images.githubusercontent.com/159967/71574961-b4fb2980-2af3-11ea-9077-b6fb1aa92e3a.png)

**Comment by mgedmin** [comment]
If you're more comfortable with the command line, you can do

    gsettings get org.gtimelog task-list-url
    gsettings set org.gtimelog task-list-url https://example.com/my-tasks.txt
    gsettings set org.gtimelog remote-task-list true
    gsettings set org.gtimelog remote-task-list false

etc.  You can see the possible key names with

    gsettings list-recursively org.gtimelog

**Comment by ChameleonScales** [comment]
Thanks, it's a lot clearer now.
I still didn't get it to work though. We used to have a gtimelogrc file for that and I used it as a reference to set it up in dconf editor.
There was no sender email in gtimelogrc. Is that mandatory?

**Comment by ChameleonScales** [comment]
Maybe the list format has changed? Mine is a list of elements in a single line separated by periods

**Comment by ChameleonScales** [comment]
Thanks, it's much clearer now.
I used dconf editor and launched gtimelog from the terminal and now I get this:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gtimelog/main.py", line 992, in gained_focus
    self.check_reload()
  File "/usr/lib/python3/dist-packages/gtimelog/main.py", line 1321, in check_reload
    if self.timelog.check_reload():
AttributeError: 'NoneType' object has no attribute 'check_reload'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gtimelog/main.py", line 979, in tasks_downloaded
    content.decode('UTF-8', 'replace').replace('\n', '\n  '))
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by mgedmin** [comment]
Oooh, that looks like a bug!  Specifically, this bug: #154.  It's fixed, but I haven't made a new release with the fix yet.

Can you try with git master?  No special installation steps are needed, just a git clone + running ./gtimelog inside.

**Comment by ChameleonScales** [comment]
worked immediately! Thank you

**Comment by kronn** [comment]
And that is the heart-warming story you want to read at this time of year :smile:
