### ISSUE TITLE
Editing hours without going into log

### ISSUE THREAD

**Issue by clrh** [gtimelog/gtimelog#169]
First, I like gtimelog, really, it is simple and what I was looking for personally, it helps me a lot.

I would love to edit hours without going into the "edit log" in "parameters".

I often forgot to add a task so I add two tasks at the same time but I would like to edit the time of the first added, maybe just in specifying when I enter it ? I don't now how, but it would be an enhancement in my daily use.

Regards,
Claire.

**Comment by mgedmin** [comment]
You're in luck!  You can enter a time followed by a task, like "12:34 something something", and it'll be recorded as if you'd entered it when the time was 12:34.  (This only works if the previously recorded task happened before 12:34.)

You can also use relative times, like "-15 something else" will be recorded as if you entered it 15 minutes ago.

This is even documented in https://gtimelog.org/docs.html, under "Correcting mistakes", but I admit that documentation is very brief and not exactly easy to find.

**Comment by clrh** [comment]
Oh great thanks :)
