### ISSUE TITLE
[ENH] Option to minimize to taskbar

### ISSUE THREAD

**Issue by ericzolf** [gtimelog/gtimelog#175]
I know that Gnome3 doesn't have it really any more, but there are extensions for this, and not everybody is using Gnome3, and it would be very nice if gtimelog could minimize itself to the taskbar instead of fully closing when the app window is closed, so that the app can quickly be re-opened without cluttering the Windows list.

**Comment by mgedmin** [comment]
I believe the default GNOME 3 keybinding for this is Super+H.  Does that work for you?  (Although it doesn't remove the app from the Alt-Tab dialog, but I'm currently on Ubuntu with their own customizations, and I'm not sure how upstream GNOME behaves.)

I personally have a custom keybinding in gnome-control-center that runs gtimelog on Super+G.  I tend to close gtimelog entirely and bring it back whenever I want to with a single key chord.

**Comment by ericzolf** [comment]
Super+H minimizes the application to (what I call) the Windows bar and not to the taskbar (as e.g. provided by the extension [topicons-plus](https://extensions.gnome.org/extension/1031/topicons/)). Creating a key binding is an alternative, as gtimelog doesn't do anything between entries... Anyway, not super important, but IMHO a nice add-on.

**Comment by mgedmin** [comment]
Ah, you want a tray icon?  There's a wishlist bug open for that: #116.
