### ISSUE TITLE
Do not sort projects/tasks in the GUI, keep config file order

### ISSUE THREAD

**Issue by ericzolf** [gtimelog/gtimelog#182]
I recently added a new project/task and placed it at the top of the list because it's now my most important one, but it always appears at the bottom of the list in the GUI because it's alphabetically so. I've of course added a few letters in front to make it work as needed, but it could be made easier.

**Comment by mgedmin** [comment]
Looking at the code, the task list loader sorts the groups but keeps the tasks of each group in the original order:
https://github.com/gtimelog/gtimelog/blob/9143f8ef509f1d2980a3e01acd18bcc6d1ca89b8/src/gtimelog/timelog.py#L1108-L1125

And I've played around with it, and the UI also doesn't do any additional sorting inside each group, but does show the groups in sorted order.

So I guess what you want is for gtimelog to stop sorting task groups?

That ought to be a simple change: change the initialization of `groups = {}` to be `groups = collections.OrderedDict()`, and change the `sorted(group.items())` call at the end to `list(group.items())`.  Then update the expected order in any unit tests that fail (I hope at least one test will fail!).

Would you like to prepare a PR?
