### ISSUE TITLE
Contents not updated on file modification if behind a symbolic link

### ISSUE THREAD

**Issue by Toover** [gtimelog/gtimelog#187]
## Motivation

Synchronize the `timelog.txt` and `tasks.txt` files online by putting them in a shared folder.

## Protocol

1. `gtimelog` is closed.
2. Move your log & task files away (here, to `~/wherever`):
```bash
mv ~/.local/share/gtimelog/timelog.txt ~/wherever/
mv ~/.local/share/gtimelog/tasks.txt ~/wherever/
```
3. Replace them with a symbolic file:
```bash
ln -s ~/wherever/timelog.txt ~/.local/share/gtimelog/timelog.txt
ln -s ~/wherever/tasks.txt ~/.local/share/gtimelog/tasks.txt
```
4. Run `gtimelog`. All the contents are found, everything is fine.
5. In the menu, select "Edit log" or "Edit tasks" (issue affects both features).
The symbolic link is resolved by the text editor (works fine with `gedit` for instance).
6. Modify the contents of the log or the tasks. Save. Close.

## Observed

The time log / tasks views remain unchanged.

## Expected

The time log / tasks are immediately updated with the edited contents.

**Comment by Toover** [comment]
At first sight, it seems that `gtimelog` subscribes to the modification of the symbolic link files (`~/.local/share/gtimelog/timelog.txt` and `~/.local/share/gtimelog/tasks.txt`), instead of resolving the linked files, and tracking their modifications.

**Comment by mgedmin** [comment]
That's strange, I'm pretty sure I remember adding code to track both the modification time of the symlink as well as the modification time of the linked file.

Could you please post the output of `gtimelog --version`?

**Comment by mgedmin** [comment]
Yeah, this was #128, and it was supposed to be fixed in 0.11.2.

**Comment by Toover** [comment]
```
~ ⌚ 9:16:29
$ gtimelog --version
GTimeLog version: 0.11
Python version: 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
GTK+ version: 3.22.30
PyGI version: 3.26.1
Data directory: /home/obfuscated/.local/share/gtimelog
Legacy config directory: /home/obfuscated/.config/gtimelog
Settings already migrated to GSettings (org.gtimelog)
```

Sorry if that's an old bug already fixed.

**Comment by mgedmin** [comment]
Ah, yes, your version was from before that bugfix.

And I'm not doing a particularly good job pushing updates into distros, or making use of FlatHub...  *sigh*

**Comment by Toover** [comment]
Don't worry, having this software work just fine is already amazing. Thank you.
