### ISSUE TITLE
Make titlebar smaller

### ISSUE THREAD

**Issue by elisdg** [gtimelog/gtimelog#205]
Hi,
I like to have gtimelog open all the time (nice tool! I use it for 3y now after trying a bunch of tools and strategies)
I reduced the size of the window already with `xdotool windowsize 0818windowid98714 600 110`
But the titlebar is still very big and takes up some screenspace:
![image](https://user-images.githubusercontent.com/15905294/105867588-8c46ab80-5ff5-11eb-9f50-952abbe512c2.png)

Can you point me how to make the titlebar smaller or toggle it completely with an (i3/keypoard)-shortcut? I tried with a ~/.config/gtk-3.0/gtk.css but this didn't do anything:
```
.header-bar.default-decoration { padding-top: 0px; padding-bottom: 0px; }
.header-bar.default-decoration .button.titlebutton { padding-top: 0px; padding-bottom: 0px; }
```
Thanks in advance

**Comment by mgedmin** [comment]
I don't know if it's possible to reduce the header bar size, sorry!
