### ISSUE TITLE
Question: Is there a way to end the day?

### ISSUE THREAD

**Issue by Lacroute** [gtimelog/gtimelog#206]
I'm wondering if I have to specify when I end the day.
I experienced some bugs this morning (second day of use). It didn't take my new `arrived **` entry as a starting point.
In fact it ignores all my saved tasks.

you can test my data
tasks.txt
```
arrived **
lunch **
break **
yescapa: daily
yescapa: point front
yescapa: point tech
yescapa: réunion
```
timelog.txt
```
2021-01-28 18:17: arrived **
2021-01-28 18:18: taf: test
2021-01-28 18:23: test: lecture doc de gtimelog
2021-01-29 9:30: arrived **
2021-01-29 9:40: yescapa: daily
2021-01-29 10:05: calendar: reunion
2021-01-29 12:50: calendar: dev
```
Am I doing something wrong?

**Comment by mgedmin** [comment]
Are you editing timelog.txt by hand?  The time format is wrong:

```
2021-01-29 9:30: arrived **
2021-01-29 9:40: yescapa: daily
```

should be

```
2021-01-29 09:30: arrived **
2021-01-29 09:40: yescapa: daily
```

Also, gtimelog writes a blank line between days, and I have plans of making those blank lines be treated as day separators, instead of relying on "virtual midnight" heuristics.  I recommend that you put in blank lines between days if you edit timelog.txt yourself, for future compatibility.

**Comment by Lacroute** [comment]
I had to edit it by hand, but the format was without the seconds originally. When I add tasks it forgets the seconds all the time.
I added blank lines, thanks for the explanation.

**Comment by Lacroute** [comment]
I updated my version of python (I was still in 2.x) and reinstalled gtimelog.
It continues to write entries without seconds but this times UI is reacting to changes. Strange thing is if I edit the entries to manually add seconds, it doesn't work anymore. I should use hte hh:mm: format.

**Comment by iaeiou** [comment]
> I should use the hh:mm: format

Yes I think so. I'm using gtimeLog since almost a year now, _without seconds_ and it works fine. I guess it's the way it's supposed to work

**Comment by mgedmin** [comment]
That's right, the time format in timelog.txt is `YYYY-MM-DD HH:MM`.  No seconds there (who brought up seconds and why?). The important bit is the hours field needs to always be two digits (`09`, not `9`).

**Comment by Lacroute** [comment]
I just brought up I don't know why. Misreading.
Thanks for the help and have a nice day
