### ISSUE TITLE
Custom timelog.txt url

### ISSUE THREAD

**Issue by ChameleonScales** [gtimelog/gtimelog#207]
I often jump between computers at work. If I could set up gtimelog to put its timelog.txt in a shared folder, I wouldn't have to pull the log from each computer back into the shared version every so often.
Is there a way to do that or otherwise could this be implemented in the settings somehow (e.g. through dconf editor)?

**Comment by mgedmin** [comment]
You can create a symlink, either of the entire ~/.gtimelog -> ~/Dropbox/gtimelog, or just of the ~/.gtimelog/timelog.txt -> ~/Dropbox/gtimelog/timelog.txt.  (Replace Dropbox with the appropriate shared folder name.)

**Comment by ChameleonScales** [comment]
That works, thanks for the tip!
