### ISSUE TITLE
'No module named gi' on Fedora 33

### ISSUE THREAD

**Issue by samtuke** [gtimelog/gtimelog#208]
Gtimelog used to work fine on Fedora but now gives the following error:

```
Traceback (most recent call last):
  File "/home/samtuke/.local/bin/gtimelog", line 6, in <module>
    from gtimelog.main import main
  File "/home/samtuke/.local/lib/python2.7/site-packages/gtimelog/main.py", line 61, in <module>
    import gi
ImportError: No module named gi
```

I've installed several packages which looked like decent candidates to provide `gi`, using both dnf and pip, so far to no avail. 

What am I missing?

**Comment by mgedmin** [comment]
I see you're still using Python 2.7.  Can you try with Python 3?  I suspect the Fedora packages for Python gobject introspection integration dropped 2.7 support already.

**Comment by ericzolf** [comment]
I guess, this issue can be closed, I use gtimelog on Fedora (currently 36) since quite a while and never got this issue. gtimelog also uses now Python 3.

> **Note:** another issue could be that the package didn't / doesn't pull the right dependency but that would be a packager issue, to be reported at https://bugzilla.redhat.com/ (but in Fedora 36, gtimelog depends on python3-gobject, so looks fine to me).
