### ISSUE TITLE
Positive time offset entry

### ISSUE THREAD

**Issue by jpsnyder** [gtimelog/gtimelog#209]
I propose there should be added syntax for adding an entry x number of minutes since the last entry.
There are many times where I forget to add an entry for a meeting or lunch before I continue on with my normal work tasks.

While I know there is an already existing `-MM` and `HH:MM` syntax (https://bugs.launchpad.net/gtimelog/+bug/291356), that requires me to either do the mental math to determine the offset from now or to do datetime math in my head. Especially if it has been a while since I forgot.

It would be nice if there was a `+MM` syntax, which offsets from the last created entry complimenting the `-MM` syntax which offsets from the current time.
This will make it easy to add in that 30 minute lunch I forgot to record: `+30 lunch **` or 1 hour meeting `+60 meeting`

**Comment by mgedmin** [comment]
That sounds like a good idea to me!

If you'd like to submit a pull request, the code that handles the `-MM` syntax is in
https://github.com/gtimelog/gtimelog/blob/e154f50c54b36d297437c3d80e1c9406fa6c11de/src/gtimelog/timelog.py#L1024-L1057
and the tests for that code are in
https://github.com/gtimelog/gtimelog/blob/master/src/gtimelog/tests/test_timelog.py#L1179-L1241

**Comment by jpsnyder** [comment]
No problem, I should be able to whip up a PR soonish.

**Comment by mgedmin** [comment]
Ah, the documentation at https://github.com/gtimelog/gtimelog/blob/master/docs/index.rst#back-dating-entries will also need a brief mention of the +MM syntax.
