### ISSUE TITLE
Soap.SessionAsync does not validate TLS certificates?!

### ISSUE THREAD

**Issue by mgedmin** [gtimelog/gtimelog#214]
https://blogs.gnome.org/mcatanzaro/2021/05/25/reminder-soupsessionsync-and-soupsessionasync-default-to-no-tls-certificate-verification/:
> The modern SoupSession class is secure by default, but the older, deprecated SoupSessionSync and SoupSessionAsync subclasses of SoupSession are not. If your code uses SoupSessionSync or SoupSessionAsync and does not set SoupSession:tls-database, SoupSession:ssl-use-system-ca-file, or SoupSession:ssl-ca-file, then you get no TLS certificate verification. This is almost always worth requesting a CVE.

and I see we have
https://github.com/gtimelog/gtimelog/blob/8e8fc4457b2914ae83d0857147cb69191f8dd12f/src/gtimelog/main.py#L173
but I don't see us setting any of the aforementioned properties anywhere.

Test plan:
- dconf write /org/gtimelog/task-list-url "'https://wrong.host.badssl.com/'
- dconf write /org/gtimelog/remote-task-list true
- witness the task load filling up with a bunch of <!DOCTYPE html> instead of failing

Fix plan:
- [x] use `Soap.Session` instead of `Soap.SessionAsync`, and hope things just work
- [ ] do we need to care about older systems?  when was Soap.Session introduced?  any other compatibility concerns?

I have tested the fix locally, and it works fine: you get an error from hosts like https://expired.badssl.com/, but download succeeds from https://badssl.com/ (which, ironically, has a good SSL certificate).

I'm about to push a fix, probably directly to master.

Cc: @andrewshadura, since you wrote the Soap-using code -- do you happen to know about any possible compatibility concerns?  I don't use remote task lists myself.

**Comment by andrewshadura** [comment]
Sorry for not replying — I somehow completely missed this.

**Comment by mgedmin** [comment]
Well, nobody complained in the last 4 and a half years, so I think it's all good.
