### ISSUE TITLE
Shortcuts window does not show up on MacOS

### ISSUE THREAD

**Issue by icemac** [gtimelog/gtimelog#220]
### What I did

I am using MacOS 12.3.1
I installed the necessary dependencies using MacPorts.
I am using the `main` branch of `gtimelog`.

### What happened

When accessing the `Keyboard Shortcuts` entry in the ꠵ menu the main `gtimelog` window gets inactive and I cannot enter anything. Pressing `esc` seems to end the invisible dialog.

Preferences and "About Time Log" do not suffer from this problem.

### What I did to debug the problem

I started `gtimelog` using `--debug` option. This just produced the following warning.

```
src/gtimelog/main.py:340: Warning: The property GtkContainer:child is deprecated and shouldn't be used anymore. It will be removed in a future version.
  builder = Gtk.Builder.new_from_file(SHORTCUTS_UI_FILE)
```

### Questions

* Is there a way to debug this kind of issues further?
* Is there anyone out there who does not have this problem?

**Comment by mgedmin** [comment]
Hmm, sounds like a GTK bug to me.  Do you have a gtk3-widget-factory binary available?  (On Ubuntu it's shipped in the gtk-3-examples package. I've no idea how GTK for MacOS is distributed.)  Can you see if the keyboard shortcuts windows works there?

**Comment by icemac** [comment]
I am no long able to reproduce the bug on an M2 machine.
