### ISSUE TITLE
.travis.yml present in MANIFEST.in, absent from repository

### ISSUE THREAD

**Issue by ericzolf** [gtimelog/gtimelog#225]
I guess, you moved from travis pipeline to GitHub actions and forgot the one entry in MANIFEST.in

Calling `./setup.py build` warns about it:

```
reading manifest template 'MANIFEST.in'
warning: no files found matching '.travis.yml'
```

I can do it, just wanted to get the issue validated.

**Comment by mgedmin** [comment]
Ah, yes, absolutely.
