### ISSUE TITLE
Autocompletion menu horizontally displaced on second screen

### ISSUE THREAD

**Issue by sfendrich** [gtimelog/gtimelog#232]
With multiple screens configured to be side-by-side, the auto-completion menu is displaced to the right, when gtimelog is shown on the second screen (tested on several screen combinations). I guess, the horizontal position is computed from the desktop width instead of the screen width.

Setup:
Gtimelog 0.11.3
Ubuntu 22.04.2 LTS
Gnome 42.5

**Comment by mgedmin** [comment]
This sounds like a GTK bug?  The GtkEntry completion APIs don't allow me to affect the position of the completion popup.

**Comment by sfendrich** [comment]
Thanks for pointing to GtkEntryCompletion! There is indeed a GTK bug report: https://gitlab.gnome.org/GNOME/gtk/-/issues/2794
