### ISSUE TITLE
Automatically "arrive"

### ISSUE THREAD

**Issue by jporzelt** [gtimelog/gtimelog#233]
Is there a way to automatically "arrive" on program startup?
Maybe there is a way of having a command line parameter like `gtimelog -t "arrive **"`?

**Comment by mgedmin** [comment]
Not currently, but I'd like to add `gtimelog --add "blah blah blah"` one of these days.

**Comment by mgedmin** [comment]
What you can currently do is use a shell script to

    printf "\n%s: arrived **\n" "$(date +'%Y-%m-%d %H:%M')" >> ~/.local/share/gtimelog/timelog.txt

(or >> ~/.gtimelog/timelog.txt if you've been using gtimelog for a long time and still have its data files in the old location.)

**Comment by jporzelt** [comment]
Wow. Thanks for the fast feedback. 
Will do so.
Have a nice weekend!
