### ISSUE TITLE
Get Total time for a specific tag/project.

### ISSUE THREAD

**Issue by jpsnyder** [gtimelog/gtimelog#243]
I was recently tasked by my work to let them know how much time I have spent working on a specific project.
Luckily, I have been tracking that project as a separate tag. Although, I just realized you can only get reports for up to the most recent month in the reports. And this project as been many months long.

Is there any quick fix script I can use or something against the log file to get the total hours accomplished for a specific tag since the beginning?

**Comment by mgedmin** [comment]
There's an unfinished PR (#142) for doing reports for a custom date range -- the missing bits are user interface for the two calendar controls.  I just check it and ... it does not appear to work any more.  (Actually, looking at the code, the plumbing to get the entered dates into the backend reporting logic was never finished, so it never worked.)

If you have monthly reports for all those months in text files somehere, you could grep for the desired tag and pipe the output to `scripts/sum.py` to compute the total sum of all the durations.

Finally, writing a custom Python script to use gtimelog's own TimeLog and Reports classes to produce a report for an arbitrary date range shouldn't be too hard.  Once you get a TimeLog(...).window_for(datetime1, datetime2), all the reports will work on the specified time range and the differences between the .monthly_report)(/.weekly_report()/.daily_report() methods are purely in text formatting.

**Comment by jpsnyder** [comment]
I looked at the date range thing, but couldn't get gtimelog to build to test it out. (Some issue with pycairo I don't care to figure out).

I was hoping someone had a script in their back pocket I could use to parse the log file.
So I ended up writing my own shown below.

In any case, it might be nice if gtimelog had a "stats" page or something which would show total counts for things. 

```python

from datetime import datetime
from pathlib import Path
import re
import sys

from tabulate import tabulate


def calculate_times(log_path):
    prev_timestamp = None
    entries = {}
    with open(log_path, "r") as log:
        for line in log.readlines():
            line = line.strip()

            match = re.match("(?P<timestamp>\d\d\d\d-\d\d-\d\d \d\d:\d\d): (?P<entry>.+)", line)
            if not match:
                continue
            timestamp = match.group("timestamp")
            entry = match.group("entry")

            timestamp = datetime.fromisoformat(timestamp)
            if not prev_timestamp:
                prev_timestamp = timestamp
            duration = timestamp - prev_timestamp
            if duration.days == 0:  # only count within the same day.
                if entry in entries:
                    entries[entry] += duration
                else:
                    entries[entry] = duration
            prev_timestamp = timestamp

    # Print summary of all entries
    tabular_data = [(entry, str(duration)) for entry, duration in entries.items()]
    print(tabulate(sorted(tabular_data), headers=("Entry", "Duration")))
    print("\n")

    # Print summary of categories
    categories = {}
    for entry, duration in entries.items():
        category, found, _ = entry.partition(":")
        if found:
            if category in categories:
                categories[category] += duration
            else:
                categories[category] = duration

    tabular_data = [(category, str(duration)) for category, duration in categories.items()]
    print(tabulate(sorted(tabular_data), headers=("Category", "Duration")))



if __name__ == "__main__":
    if len(sys.argv) > 1:
        path = Path(sys.argv[1])
    else:
        path = Path("~/.local/share/gtimelog/timelog.txt").expanduser()

    calculate_times(path)
```
