### ISSUE TITLE
Remember window and task pane sizes when stopping GTimeLog

### ISSUE THREAD

**Issue by tiramiseb** [gtimelog/gtimelog#30]
Hello,

I'm using GTimeLog 0.9.1 from the official package in Ubuntu 14.10.

Every time I start GTimeLog, I have to resize the window and the tasks pane : my tasks names are long and some begin with the same words, so a small task pane is a pain for identifying the task I want to click on.

GTimeLog should store the size of the window and the width of the tasks pane in order to restore an identical window.

**Comment by mgedmin** [comment]
This is implemented in the experimental-ui branch mockup.
