### ISSUE TITLE
Modernize the UI

### ISSUE THREAD

**Issue by mgedmin** [gtimelog/gtimelog#31]
I want gtimelog to look at home in a modern GNOME 3 desktop.  This means

- header bars
- app menu
- new-style about dialog

Something like this:
![./mockup.py from the experimental-ui branch](https://cloud.githubusercontent.com/assets/159967/9703915/cd4b2668-549a-11e5-936c-e38eea1d3bc7.png)

Checklist:

- [x] mock up some UI in glade
- [x] implement it
- [ ] ~~perhaps pay attention to `gtk_application_prefers_app_menu()` and keep the old menu bar if that returns False?~~ (nah, unless somebody convinces me)
- [x] test in a non-GNOME environment
- [x] test on stable versions of several distros (Ubuntu 14.04, ~~Debian stable, Fedora something?~~) to see if I'm using any bleeding-edge APIs unnecessarily

Implementation in the experimental-ui branch (use `./mockup.py` instead of `./gtimelog`):

- [x] basic UI
- [x] history browsing
- [x] task entry
- [ ] ~~get rid of scrolling animations during task entry~~ (or don't, I think I can live with it)
- [x] history completion
- [x] task pane
- [x] support for remote task lists (sort of; there are rough edges and no UI)
- [x] previewing reports
- [x] sending reports via email
- [x] error handling when report sending fails
- [x] help page documenting keyboard shortcuts
- [x] preferences dialog
- [x] persistent view settings (task pane on/off at the very least) in gsettings
- [x] command-line option handling (--version)
- [x] fix warnings
- [x] add back Python 2 support
- [x] remove custom CSS loading code; I didn't end up using any custom CSS
- [ ] ~~access keys for all menus and other widgets~~ (not if I can't see them)

**Comment by shirishag75** [comment]
Do you mean this :-

    [$] ./gtimelog
                                                                                                                          
    ./src/gtimelog/main.py:234: Warning: The property GtkButton:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
      builder.add_from_file(ui_file)
    ./src/gtimelog/main.py:234: Warning: The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
      builder.add_from_file(ui_file)
    ./src/gtimelog/main.py:234: Warning: The property GtkSettings:gtk-menu-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
      builder.add_from_file(ui_file)
    ./src/gtimelog/main.py:234: Warning: The property GtkToolButton:stock-id is deprecated and shouldn't be used anymore. It will be removed in a future version.
      builder.add_from_file(ui_file)
    ./src/gtimelog/main.py:234: Warning: The property GtkMisc:xpad is deprecated and shouldn't be used anymore. It will be removed in a future version.
      builder.add_from_file(ui_file)
    
I just cloned and ran it and all of the above came.

**Comment by mgedmin** [comment]
@shirishag75 what's your Gtk+ version?  I don't get these warnings with 3.14.

**Comment by shirishag75** [comment]
@mgedmin I am guessing this is what you are looking for :-

    [$] dpkg -l libgtk-3-0 libgtk-3-bin libgtk-3-common libgtk-3-dev                                                                   
    
    Desired=Unknown/Install/Remove/Purge/Hold
    | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
    |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
    ||/ Name                           Version              Architecture         Description
    +++-==============================-====================-====================-=================================================================
    ii  libgtk-3-0:amd64               3.14.5-1             amd64                GTK+ graphical user interface library
    ii  libgtk-3-bin                   3.14.5-1             amd64                programs for the GTK+ graphical user interface library
    ii  libgtk-3-common                3.14.5-1             all                  common files for the GTK+ graphical user interface library
    ii  libgtk-3-dev:amd64             3.14.5-1             amd64                development files for the GTK+ library

**Comment by mgedmin** [comment]
Huh.  I'm on libgtk-3-0 version 3.14.4-0ubuntu1~utopic3 (Ubuntu 14.10 + ppa:gnome3-team/gnome3-staging).  No warnings here.

I'll upgrade to Ubuntu 15.04 in two days (when it's released) and see what happens with Gtk+ 3.14.12.

**Comment by mgedmin** [comment]
(Anyway this bug was supposed to be about look & feel, not warnings.  Please file a new bug if you get any of those!)

**Comment by shirishag75** [comment]
@mgedmin thanx, did just that https://github.com/gtimelog/gtimelog/issues/37

**Comment by mgedmin** [comment]
Musings: should I maybe use a WebKit.WebView to render the time log instead?  Here's an example: http://www.kryogenix.org/days/2014/03/03/writing-a-simple-desktop-widget-for-ubuntu/

**Comment by mgedmin** [comment]
Anyway, if anyone's interested, feel free to check out the `experimental-ui` branch.  Run ./mockup.py instead of ./gtimelog.  It's not fully functional yet: you can browse the log, but you cannot add new things to it.

**Comment by shirishag75** [comment]
Nice, very nice .  Although got 2 deprecated warnings there as well. 

    ./mockup.py:266: Warning: The property GtkWidget:margin-left is deprecated and shouldn't be used anymore. It will be removed in a future version.
      builder = Gtk.Builder.new_from_file(UI_FILE)
    ./mockup.py:266: Warning: The property GtkWidget:margin-right is deprecated and shouldn't be used anymore. It will be removed in a future version.
      builder = Gtk.Builder.new_from_file(UI_FILE)

**Comment by mgedmin** [comment]
Thanks for letting me know!  I keep forgetting that Ubuntu disables all Gtk warnings by default.

**Comment by shirishag75** [comment]
So you are doing it in GTK, must say it looks sweet :)

**Comment by mgedmin** [comment]
Welp: https://bugzilla.gnome.org/show_bug.cgi?id=722514 (Glade should use margin-start/end instead of left/right).

While searching for this I also found https://bugzilla.gnome.org/show_bug.cgi?id=744095, which I've seen.

**Comment by shirishag75** [comment]
umm...ok glade, good :)

**Comment by mgedmin** [comment]
There's a bug in the new code: if you leave gtimelog running overnight (showing a daily view of today), the next day when you start entering new stuff they get appended to the end -- you still see yesterday's events above it.

There's code to not do that, but it's buggy.
