### ISSUE TITLE
Create .desktop file

### ISSUE THREAD

**Issue by chronossc** [gtimelog/gtimelog#32]
Hello Marius,  I have using gtimelog again and I'm very happy btw.

gtimelog has been excelent in a dark theme QT environment as you can see in image below:

![image](https://cloud.githubusercontent.com/assets/208856/6861836/e9ef186a-d41b-11e4-8868-759567dd67c8.png)

However, it don't have a .desktop file and I believe that because of that it does not appear on KDE menus as you see:

![image](https://cloud.githubusercontent.com/assets/208856/6861880/a7b1f336-d41c-11e4-8bf1-6b29503cf331.png)

[]'s

**Comment by mgedmin** [comment]
There's a [gtimelog.desktop](https://github.com/gtimelog/gtimelog/blob/master/gtimelog.desktop) in master, and the Debian package installs it.

The .desktop file is not installed when you `pip install gtimelog`, and I don't think it's possible to install it using pip, at least not cleanly.

Could you provide more information about how you installed gtimelog?

**Comment by chronossc** [comment]
I using it via pip install, actually via a gtimelog-git PKGBUILD for ArchLinux based distros :) (https://aur.archlinux.org/packages/gtimelog-git/)

Now that u told about .desktop I have checked and I need to copy it to right place, because it is not a setup.py install task, but a package manager task.

For the register, if someone install via `pip install` in the system, make this copy:

```
cp gtimelog.desktop /usr/share/applications/gtimelog.desktop
cp src/gtimelog/gtimelog.png /usr/share/icons/hicolor/48x48/apps/gtimelog.png
```
I will do that today, so u can close that issue.

One more thing Marius, I have found that `gtimelog-large.png` is in 300px x 300px resolution and accepted resolutions here are:

``` 
8x8/
16x16
20x20
22x22
24x24
32x32
36x36
40x40
42x42
49x49
64x64
72x72
80x80
96x96
128x128
192x192
256x256
384x384 <<
512x512
1024x1024
scalable/
```

When u have time is cool to fix it or made a scalable icon :).

Thank you!

**Comment by mgedmin** [comment]
I'd love to get a scalable icon.  Alas, I'm not an artist. :(

**Comment by chronossc** [comment]
What 'image' of icon you want :)? I did that to use in my system so it looks better (just merged two vectorial free icons I have found on web):

![clock-time-3-512](https://cloud.githubusercontent.com/assets/208856/6879938/a4105258-d4f4-11e4-9a2a-738324e3b8b1.png)

I use it in blank for my dark color scheme:

![image](https://cloud.githubusercontent.com/assets/208856/6879952/d2ba2862-d4f5-11e4-8bf8-fca45208a716.png)

The original icon page is http://simpleicon.com/clock-time-3.html

**Comment by mgedmin** [comment]
> What 'image' of icon you want :)?

I've no idea, which is part of my problem! :(

I'd like it to be pretty and fit in well with GNOME.  Oh, and work well with light backgrounds as well as dark backgrounds.
