### ISSUE TITLE
What to do if you want to make working hours different ?

### ISSUE THREAD

**Issue by shirishag75** [gtimelog/gtimelog#35]
Hi there, 
What to do if you want to make the working hours different, other than the 8 hours shown as default. 

Is it just need to change in `~/gtimelog/src/gtimelog/settings.py`

    hours = 8

Update: Nope changing that to 6 hours or 4 hours doesn't do anything for making the number of hours done in day :(

**Comment by mgedmin** [comment]
settings.py has the default value that will be written to the config file on first startup (when the config file doesn't exist).

`~/.config/gtimelogrc` has the configured value that overrides the default value.

Change `~/.config/gtimelogrc`.
