### ISSUE TITLE
which config file ?

### ISSUE THREAD

**Issue by shirishag75** [gtimelog/gtimelog#36]
From https://github.com/gtimelog/gtimelog/blob/master/docs/formats.rst

got the following :-

>It also advises you how much time you still have to work today to get 8 hours of work done, and how much time is left just to have spent a workday at the office (the number of hours in a day is configurable in the config file).

Pray tell which config file are you talking about ?

    ~/games/gtimelog]
     
    └─[$] ls                                                                                                                              
    CONTRIBUTING.rst  docs gtimelog.desktop gtimelog.rst NEWS.rst runtests   setup.py  tox.ini CONTRIBUTORS.rst gtimelog gtimelogrc.example Makefile NOTES.rst scripts src COPYING gtimelog.appdata.xml gtimelogrc.rst MANIFEST.in README.rst setup.cfg TODO.rst

Are you talking about the workdays.py script in scripts directory or somewhere else ?

**Comment by shirishag75** [comment]
aha, it is in `~/.config/gtimelog/gtimelogrc` changed that and it worked.

**Comment by mgedmin** [comment]
Eventually there'll be a Preferences dialog for setting this.

(If somebody sent me some mockups or Glade .ui files, that could speed things up)
