### ISSUE TITLE
Could sub tasks have sub task please?

### ISSUE THREAD

**Issue by soldersplash** [gtimelog/gtimelog#40]
The tasks and sub tasks element is really useful. However, further branching of tasks would be even more useful :)
Kind regards,
Daniel.

**Comment by mgedmin** [comment]
GTiimeLog has subtasks?  Could you refresh my memory?

Are you talking about the Tasks sidebar?

**Comment by mgedmin** [comment]
I'm closing this, since it's too vague for concrete action, and you never responded to my clarification request.
