### ISSUE TITLE
Warnings about deprecated functions while running gtimelog

### ISSUE THREAD

**Issue by shirishag75** [gtimelog/gtimelog#41]
Got a few warnings on a different system, see if you fix it :-

$ gtimelog
/usr/lib/python3/dist-packages/gtimelog/main.py:424: Warning: The property GtkButton:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
  builder.add_from_file(ui_file)
/usr/lib/python3/dist-packages/gtimelog/main.py:424: Warning: The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
  builder.add_from_file(ui_file)
/usr/lib/python3/dist-packages/gtimelog/main.py:424: Warning: The property GtkSettings:gtk-menu-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
  builder.add_from_file(ui_file)
/usr/lib/python3/dist-packages/gtimelog/main.py:424: Warning: The property GtkToolButton:stock-id is deprecated and shouldn't be used anymore. It will be removed in a future version.
  builder.add_from_file(ui_file)
/usr/lib/python3/dist-packages/gtimelog/main.py:424: Warning: The property GtkMisc:xpad is deprecated and shouldn't be used anymore. It will be removed in a future version.
  builder.add_from_file(ui_file)

$ python3 --version
Python 3.4.3+

**Comment by mgedmin** [comment]
Can you include the full output of `gtimelog --debug` please?

**Comment by mgedmin** [comment]
Hm, I think I fixed all of these warnings while I was fixing #37.

Are you running gtimelog master?  I haven't made a release to PyPI in a long time (mostly because gtimelog master requires a rather recent-ish GTK+).

**Comment by shirishag75** [comment]
oops... I was running stock debian one that time. Can you make a new release so I can haunt the maintainer into pushing that one into debian ?

**Comment by mgedmin** [comment]
Will try to release 0.10 soon.
