### ISSUE TITLE
How to generate ~/.gtimelog/gtimelogrc ?

### ISSUE THREAD

**Issue by shirishag75** [gtimelog/gtimelog#42]
Dear Marius, 
 installed on another system and not able to have ~/.gtimelog/gtimelogrc . I get nada, nothing. 

The timelog.txt are at ~/.local/share/gtimelog/timelog.txt but cannot find ~/.gtimelog/gimelogrc . Can you help with the above ?

**Comment by mgedmin** [comment]
Look for `~/.config/gtimelog/gtimelogrc`.

**Comment by mgedmin** [comment]
For completeness' sake I should probably also mention `gtimelog --sample-config`:
```
mg@platonas: ~ $ gtimelog --sample-config
Sample configuration file written to gtimelogrc.sample
Edit it and save as /home/mg/.config/gtimelog/gtimelogrc
```
