### ISSUE TITLE
GDK complains out being imported without specifying version. 

### ISSUE THREAD

**Issue by shirishag75** [gtimelog/gtimelog#48]
While running mockup.py came across this :-

    $ ./mockup.py 
    ./mockup.py:49: ImportWarning: Gdk was imported without specifying a version first. Use gi.require_version('Gdk', '3.0') before import to ensure that the right version gets loaded.
      from gi.repository import Gdk

Look forward to fix therein as well,

**Comment by mgedmin** [comment]
How can I reproduce this?  I've set `G_ENABLE_DIAGNOSTIC=1` in my environment, and I don't see any warnings :/

**Comment by mgedmin** [comment]
I have gir1.2-gtk-2.0 installed alongside gir1.2-gtk-3.0.  There are two Gdk typelibs on my system:

- /usr/lib/girepository-1.0/Gdk-2.0.typelib
- /usr/lib/x86_64-linux-gnu/girepository-1.0/Gdk-3.0.typelib

I don't get this warning.

**Comment by shirishag75** [comment]
I think this is not a glade but something else, see https://github.com/innstereo/innstereo/issues/51 . Think it's the same/similar issue. Guess this is coming from gtk3.16 as I don't have gtk3.18 at my end though.

**Comment by mgedmin** [comment]
Hm.  Judging from https://bugzilla.gnome.org/show_bug.cgi?id=727379 I should be ok if I `gi.require_version('Gtk', '3.0')` (which I already do), and then import Gtk _first_ (which I don't, for silly startup time measurement reasons).

**Comment by mgedmin** [comment]
Can you test my fix?

**Comment by mgedmin** [comment]
Ah!  The warning was introduced in https://github.com/gnome/pygobject/commit/2048dc8d1d708abce7037f96483c6d776567d6b5, which means my pygobject (3.14.0) is too old to have it.

**Comment by mgedmin** [comment]
Ok, I built pygobject with jhbuild and can now confirm that there's no import warning in the current code.  (But a PyGIWarning shows up if I remove the require_version call.)

**Comment by shirishag75** [comment]
yup, just tested it, sorry have been busy, works good :)
