### ISSUE TITLE
Fails ungracefully when the compiled schema is missing

### ISSUE THREAD

**Issue by shirishag75** [gtimelog/gtimelog#55]
Hi there, 

Just pulled in 0a46a4e2 and came across this :-

    $ ./mockup.py 
    
    (gtimelog:10322): GLib-GIO-ERROR **: Settings schema 'org.gtimelog' is not installed
    
    Trace/breakpoint trap
    
Can you please look into this ?

**Comment by mgedmin** [comment]
You need to run `make` to compile the gsettings schema.

**Comment by shirishag75** [comment]
I did that and came across this :-

    ~/games/gtimelog$ make
    rst2man gtimelog.rst > gtimelog.1
    rst2man gtimelogrc.rst > gtimelogrc.5
    glib-compile-schemas .
    
    $ ./mockup.py
    Traceback (most recent call last):
      File "./mockup.py", line 157, in do_command_line
        self.do_activate()
      File "./mockup.py", line 235, in do_activate
        window = Window(self)
      File "./mockup.py", line 411, in __init__
        self.load_settings()
      File "./mockup.py", line 457, in load_settings
        self.gsettings.set_string('sender', old_settings.sender)
    TypeError: Must be string, not bytes

**Comment by mgedmin** [comment]
I believe that is #54, but I don't quite understand why it happens.

In the mean time, as a workaround, you can try `python2.7 mockup.py`.
