### ISSUE TITLE
Bug: Report window window background transparent

### ISSUE THREAD

**Issue by laureenas** [gtimelog/gtimelog#62]
Repro:
Open Menu -> Report

Expected: window shows report

Got: window background is gone, only title bar and window fields show:  

![image](https://cloud.githubusercontent.com/assets/4104268/9844275/9452ffbc-5aca-11e5-9219-0e969b308e5f.png)

**Comment by mgedmin** [comment]
Ouch.  I'd hoped this was a VirtualBox video driver bug :(

**Comment by mgedmin** [comment]
Upstream bug: https://bugzilla.gnome.org/show_bug.cgi?id=733027

**Comment by mgedmin** [comment]
Upstream fix: https://github.com/GNOME/gtk/commit/02ccfb5d62430590b11b2d3e34b6100e4a6ddcda

Fixed in GTK+ 3.14.

**Comment by laureenas** [comment]
The same issue is observable on the time sheet pane as well.

**Comment by mgedmin** [comment]
Plan: connect to the 'draw' signal of the GtkStack and draw a background before returning False.  If that fails (e.g. if the signal is called after the stack's children were drawn), try subclassing the widget and overriding do_draw().

**Comment by mgedmin** [comment]
Fixed!
![ekrano nuotrauka is 2015-09-16 13-08-35](https://cloud.githubusercontent.com/assets/159967/9902022/121c372e-5c74-11e5-881c-e01f8d3149ef.png)

**Comment by mgedmin** [comment]
Fixed in d3752174cdf0b9a75ec34f559c8c970b41b8690c (where I typoed the bug number).

**Comment by mgedmin** [comment]
https://bugs.launchpad.net/ubuntu/+source/ubuntu-themes/+bug/1285783 was very useful in getting the workaround working.
