### ISSUE TITLE
Report view should use a monospace font

### ISSUE THREAD

**Issue by mgedmin** [gtimelog/gtimelog#65]
This is broken in the GTK+ 3.10 fallback .ui file, since GtkTextView didn't have a `monospace` property back then.  (See screenshot in #62.)

Perhaps there's another way?  E.g. wrap the entire text in a tag that has a font family attribute.

**Comment by mgedmin** [comment]
Apparently I can use [Gtk.Widget.override_font()](http://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Widget.html#Gtk.Widget.override_font), but it's deprecated since GTK+ 3.16.  Which is totally not a problem!

Now, how do I get the system monospace font as a Pango.FontDescriptor?

**Comment by mgedmin** [comment]
Coincidentally, GtkTextView::monospace showed up in 3.16 also.

(And the Adwaita CSS hardcodes `.monospace: { font-family: Monospace; }`, so forget tweakable font settings, apparently.)

**Comment by kronn** [comment]
:+1: thank you for this.
