### ISSUE TITLE
Crash on startup GLib-GIO-ERROR

### ISSUE THREAD

**Issue by laureenas** [gtimelog/gtimelog#76]
~/src/gtimelog$ ./gtimelog 

(gtimelog:20431): GLib-GIO-ERROR **: Settings schema 'org.gtimelog' does not contain a key named 'gtk-completion'
Trace/breakpoint trap (core dumped)

**Comment by laureenas** [comment]
Ubuntu 14.04
branch: master
commit: 889c49f7bc2e315f40fc5e58cdc2a354591bba40

**Comment by mgedmin** [comment]
Run `make` to re-build the schema.
