### ISSUE TITLE
Daily/weekly etc reports do not work in Ubuntu 14.04

### ISSUE THREAD

**Issue by rapmankin** [gtimelog/gtimelog#80]
Generating a daily/weekly report in Ubuntu opens a terminal window, but does not do anything. I presume that there is some sort of package dependency issue, but I have  no way of diagnosing it.

The only report that works 'complete report in spreadsheet, however if I quit LibreOffice with ctrl-Q, it also quits gtimelog.

Version is 0.9.1

**Comment by mgedmin** [comment]
By default gtimelog launches `mutt` in a terminal.  You can specify any other email client you like in `~/.config/gtimelog/gtimelogrc` (or `~/.gtimelog/gtimelogrc`), provided that it can accept a filename of a prepared email template on the command line.

It doesn't have to be an email client; e.g. you can use `mailer = gedit %s`.

The part there closing LibreOffice makes gtimelog quit is strange.  If you can get me the terminal output of gtimelog when it does that and file another bug, I'd appreciate it.

Incidentally, you may want to try the current git master: it's supposed to work on 14.04 LTS, and it has its own built-in report viewer/email sender.  There are no packages yet, but it should run from a git checkout (`make run`).

**Comment by rapmankin** [comment]
Thank you for the prompt response.

I do not have mutt installed and it is therefore presumably not a
dependency in the ubuntu .deb package. I substituted xedit, and that
works; mailx did not.

As to quitting LO. If I quite with ^Q there is no output from gtimelog.
If I quit using the menu 'file>exit' option all is sweetness and light,
and gtimelog stays up. May be a problem between user and keyboard :)
We'll park it for now until I get more  info.

**Comment by mgedmin** [comment]
> I do not have mutt installed and it is therefore presumably not a
dependency in the ubuntu .deb package.

IIRC mutt was listed in Recommends?  There was [a bug open about that being insufficient](https://bugs.launchpad.net/ubuntu/+source/gtimelog/+bug/221362).  The upcoming 0.11 version will fix that.
