### ISSUE TITLE
Report editor does not use a monospace font

### ISSUE THREAD

**Issue by mgedmin** [gtimelog/gtimelog#81]
Noticed it this morning:
![ekrano nuotrauka is 2016-01-04 11-01-42](https://cloud.githubusercontent.com/assets/159967/12086401/8e60be2c-b2d2-11e5-9678-04362cd9da74.png)

**Comment by mgedmin** [comment]
Explanation:
- I create a ReportView instance
- it calls self.set_monospace(True)
- I then call swap_widget() to replace the generic TextView loaded from the .ui file with my custom subclass
- swap_widget() copies all the properties (including `monospace`, which defaults to False) from the .ui file into my control

15d00c639ac54c7a60829a65a52f6a579573c5f7 does it correctly.

**Comment by menesis** [comment]
On Ubuntu 15.10 report editor used a monospace font, until this change.

**Comment by mgedmin** [comment]
@menesis: can you run `make` and tell me if that fixes your problem?

**Comment by mgedmin** [comment]
Wait, no I'm confused again.

[The documentation](https://github.com/gtimelog/gtimelog/issues/81#issuecomment-170556071) says Gtk.TextView.set_monospace() showed up in GTK+ version 3.16.  Ubuntu 15.10 has GTK+ 3.14.  Therefore we should be using the `override_font()` path.

**Comment by mgedmin** [comment]
I need a way to install chroots or something with various Ubuntu versions so I can test stuff like this.

(Previous attempts with to use Vagrant VMs and Docker containers as test systems were failures.)

**Comment by mgedmin** [comment]
Ok, I've got a wily chroot.  I can run gtimelog master in it, and I see the report editor using a monospace font.

What's the bug?

**Comment by mgedmin** [comment]
Ok.  The issue is that the `GtkTextView::monospace` property does not work with some GTK+ themes (such as Ambiance/Radiance), because *apparently* it's converted into a monospace font using theme CSS.  Which is just *brilliant*.
