### ISSUE TITLE
gtimelog on Windows 7

### ISSUE THREAD

**Issue by tunkaflux** [gtimelog/gtimelog#95]
Hello,

I'm trying to run gtimelog on Windows 7, but no success so far.
I installed PyGObject for Windows (https://sourceforge.net/projects/pygobjectwin32/files/pygi-aio-3.18.2_rev10-setup_84c21bc2679ff32e73de38cbaa6ef6d30c628ae5.exe/download) and then installed gtimelog via pip3. When I then run gtimelog in a command window, I get no output whatsoever and the command prompt just returns without any error. My Python version is 3.4.4.

Any idea on how I can further troubleshoot this?

**Comment by mgedmin** [comment]
No output whatsoever seems *very* strange.

When I run `python gtimelog` in a git master checkout on Windows 2012 Server, I get the following error:
```
Traceback (most recent call last):
  File ".\src\gtimelog\main.py", line 1903, in main
    locale.bindtextdomain('gtimelog', LOCALE_DIR)
AttributeError: 'module' object has no attribute 'bindtextdomain'
```

(This on Python 2.7.  When I attempt the same with Python 3.5, I get the expected "No module named 'gi'" because I don't have PyGObject installed yet.)

**Comment by mgedmin** [comment]
I've installed PyGObject from the sourceforge link for all my Python versions (except it failed to see Python 3.5), with GTK+ and Pango bindings.  Now `python3.4 gtimelog`, instead of failing with "No module named 'gi'", fails with "module object has no attributte bindtextdomain".

**Comment by mgedmin** [comment]
Wheee `locale.bindtextdomain()` is not documented and is missing on Windows.
See also http://stackoverflow.com/questions/32037573/load-gtk-glade-translations-in-windows-using-python-pygobject

**Comment by mgedmin** [comment]
I've committed a [workaround for the `bindtextdomain()` problem](https://github.com/gtimelog/gtimelog/commit/29e4cf65eba11246d6563e9c8a799cc4f9ce485e), and now I'm getting a 

```
WARNING: GSettings schema for org.gtimelog is missing!  If you're running from a source checkout, be sure to run 'make'.
```

What this means is that I need to run `glib-compile-schemas .` to compile [org.gtimelog.gschema.xml](https://github.com/gtimelog/gtimelog/blob/master/org.gtimelog.gschema.xml) into `gschemas.compiled`.  I don't know if the PyGObjectWin32 distribution ships `glib-compile-schemas.exe` or where it installs it.

I don't know if `gschemas.compiled` is a standard format that I could compile once on my Linux box and maybe include in source tarballs, or if it depends on things like architecture and GTK+ version.

**Comment by tunkaflux** [comment]
Ok, wow :) Sorry for setting you on a bug hunt like this.

I do have glib-compile-schemas.exe installed in C:\Python34\Lib\site-packages\gnome. It most likely came from PyGObjectWin32 as I didn't install anything else.

**Comment by mgedmin** [comment]
I've had some success!
![ekrano nuotrauka is 2016-10-07 20-06-55](https://cloud.githubusercontent.com/assets/159967/19198821/abd2b830-8cc9-11e6-88e9-495ecee87faf.png)

It has long been my desire to have gtimelog run `glib-compile-schemas` on demand automatically, without instructing the user to run `make`, and current master does so.

**Comment by mgedmin** [comment]
Things that do not work:
- Editing the timelog or tasks.txt:
![ekrano nuotrauka is 2016-10-07 20-10-17](https://cloud.githubusercontent.com/assets/159967/19198901/1a577bce-8cca-11e6-844d-8eb38f9db7c1.png)
- Sending reports via email (`/usr/bin/sendmail` does not exist)
- Translations of some text (the locale.bindtextdomain() thing mentioned above)
- This traceback visible in the console:
![ekrano nuotrauka is 2016-10-07 20-11-25](https://cloud.githubusercontent.com/assets/159967/19198960/5508a07c-8cca-11e6-88ff-fe8bd2f00e60.png)

**Comment by mgedmin** [comment]
The "Invalid format string" is produced by `strftime("%-d")` which gives me dates without a 0 prefix on Linux (e.g. today is "7", while "%d" would produce "07").

**Comment by mgedmin** [comment]
IMHO the notepad problem is a bug in GTK+:

```python
    def on_edit_log(self, action, parameter):
        filename = Settings().get_timelog_file()
        uri = GLib.filename_to_uri(filename, None)
        self.create_if_missing(filename)
        Gtk.show_uri(None, uri, Gdk.CURRENT_TIME)
```

since it's Glib that decides how to convert a filename into a `file:///` URL, and then GTK+ that decides to run notepad.exe without converting it back.

Unless maybe there's some other API that asks GTK+ to run the system default program for opening a `.txt` file that I'm missing?  One that takes a filename instead of a URL?

**Comment by mgedmin** [comment]
At this point I'm running out of steam.  gtimelog on Windows seems possible, but to make it actually usable (apart from fixing the bugs mentiond above) there ought to be an installer-type thing that bundles enough CPython and GTK+ runtime to make it work.  Maybe py2exe could be convinced to work?

Packaging is not my strong side.  I haven't even figured out how I'm going to package this for Linux yet...

**Comment by tunkaflux** [comment]
Thank you for your help so far! I've only installed python3 and PyGObjectWin32 and it seems you're almost there :)
Isn't pip a good way to install this? Or am I missing something?

**Comment by mgedmin** [comment]
If I try the 0.10 branch from git, I get `ValueError: Namespace AppIndicator3 not available` from `gi.require_version('AppIndicator', '0.1')`.  Augh!  That `require_version` is there to suppress a deprecation warning; AppIndicator is an _optional_ requirement and `gtimelog` should run fine without it.

**Comment by mgedmin** [comment]
Can you try 0.10.3 from PyPI that I've just pushed?
![ekrano nuotrauka is 2016-10-07 21-59-07](https://cloud.githubusercontent.com/assets/159967/19202068/4ef82e82-8cd9-11e6-9d74-83d0e72bfaae.png)

**Comment by tunkaflux** [comment]
Removed 0.10.2 via pip and installed 0.10.3. Success! :)

![gtimelog_ss](https://cloud.githubusercontent.com/assets/4215920/19202219/19883d26-8c86-11e6-8c5f-8c3fa63e8931.png)
